Repository semantic-release/env-ci, pull requests merged in 2018-09, with the labels that each got.

#55 feat: support Buddy CI
  README.md
  index.js
  lib/buddy.js
  package.json
  test/buddy.test.js
  test/index.test.js
Labels: in progress, new ci

#56 feat: support custom `env` and `cwd` options
  README.md
  index.js
  lib/appveyor.js
  lib/bamboo.js
  lib/bitbucket.js
  lib/bitrise.js
  lib/buddy.js
  lib/buildkite.js
  lib/circleci.js
  lib/cirrus.js
  lib/codebuild.js
  lib/codeship.js
  lib/drone.js
  lib/git.js
  lib/gitlab.js
  lib/jenkins.js
  lib/semaphore.js
  lib/shippable.js
  lib/teamcity.js
  lib/travis.js
  lib/vsts.js
  lib/wercker.js
  package.json
  test/appveyor.test.js
  test/bamboo.test.js
  test/bitbucket.test.js
  test/bitrise.test.js
  test/buddy.test.js
  test/buildkite.test.js
  test/circleci.test.js
  test/cirrus.test.js
  test/codebuild.test.js
  test/codeship.test.js
  test/drone.test.js
  test/git.test.js
  test/gitlab.test.js
  test/helpers/git-utils.js
  test/index.test.js
  test/jenkins.test.js
  test/semaphore.test.js
  test/shippable.test.js
  test/teamcity.test.js
  test/travis.test.js
  test/vsts.test.js
  test/wercker.test.js
Labels: feature, in progress

#60 docs: better indicate CodeBuild limitations
  README.md
Labels: in progress

#57 Support for Sail CI
  README.md
  index.js
  lib/sail.js
  package.json
  test/index.test.js
  test/sail.test.js
Labels: in progress, new ci

#62 test: add `services` to test coverage
  package.json
Labels: in progress

#63 feat: add `buildUrl` and `jobUrl` for Travis
  README.md
  services/travis.js
  test/services/travis.test.js
Labels: in progress
